const phrases = [
    "You're not just using a website, you're making the future.",
    "A highly developed game website designed for you.",
    "A professional popular game website.",
"Very high effort unblocked games site: https://suprcolgams2.idek29879890.repl.co",
    "We're a sensation, not just a website.",
    "Join the fun and level up your gaming experience!",
    "Enter a world of enless gaming possiblities.",
    "Get your game on with our awesome selection of addicting games.",
    "Unleash the inner gamer and dominate the competition.",
    "I can't guarantee ChatGPT did not write these.",
    "Get ready to play hard and win big.",
    "Challenge yourself with our thrilling games and conquer them all!",
    "Step into our world and discover your new favorite game.",
    "Unleash your gaming prowess and become a legend.",
    "Don't just play the game, be the game.",
    "Game on and let the adventure begin.",
    "Find your next obession among our epic games!",
    "Game your face off",
    "Get lost in a world of excitement and endless possibilities!",
    "Play hard, level up, and dominate the competition.",
    "i need new ideas, join my discord to help! psst.. the invite link is on the game page..",
    "For students, by students.",
    "Challenge yourself to new heights and conquer the games.",
    "Join the community of passionate gamers and have a blast. Discord: dsc.gg/outred",
    "Discover new worlds and embark on thrilling quests!",
    "Get ready to immerse yourself in the ultimate gaming experience!",
    "From casual to hardcore, we've got games for every player.",
    "Ready to level up your gaming skills? We've got you covered!",
"CCR Astra is a crybaby discord mod",
"Pirated GTA3 for Windows: https://tinyurl.com/freegta3ig",
    "Made with VS Code!",
    "Our games are not just entertainment, they're a lifestyle.",
    "Did you know this website started in 2022?",
    "Find your perfect game and dominate the digital world.",
    "Become a master gamer and lead your team to victory!",
    "Embark on epic adventures and conquer virtual realms!",
    "Join the Discord server and engage with an awesome community!",
    "open the nor",
    "Is it just me? Dang.",
    "Definately high quality games...",
    "Now with an unblocker!",
    "reeeeeeeeeeeeee",
    "I have 20 million power in Rise of Kingdoms!!!",
    "#OutRed4Life",
    "As simple as possible this site is.",
    "Your hub to cure boredness",
    "Hey.. Gaming in class again I see",
    "By using this site, you are helping build the next generation of bozos",
    "Gen Z is screwed",
    "You're not just using a website, you're building the future.",
    "wOwZeRs",
    "Tip: Refresh for a new message",
    "Tip: Go touch some grass",
    "Made with love from OutRed",
    "I want to be a bozo, wait! I am a bozo...",
    "Redbull gives you wings!",
    "Redbull gives you wings! (or does it??)",
    "Your IP is: 12.34.56.78",
"Also check out https://braintease.outred.dev!",
    "Whoah new UI. Crazy.",
    "Lorem Ipsum",
    "Join today at Hustlers Universi-- I mean OutRed Games Premium..",
    "Byeeeeeeeeeeeee",
    "Tourner Dans Le Vide",
    "Tator Tots... tasty!",
    "What color is your bugatti?",
    "Be a Top G",
    "lol",
    "I ran out of ideas.",
    "I need more of these...",
    "urmom hahaha",
    "Tip: Play more games",
    "Tip: Change the theme in settings! (coming soon)",
    "3kh0 says: Beans",
    "Simon says: go touch some grass",
    "You have been Ohioed",
    "Down in Ohio, swag like Ohio",
    "What color is your Bugatti?",
    "Do some pushups",
    "Bottom G",
    "Scientific proven fact: Game more and it increases your IQ",
    "Brisket... Mmmmm..",
    "My power bill is insane!",
    "LECOCO FOR PRESIDENT!!!",
    "Certified Idiot",
    "brrrrr, brrr , brrr, eeeee!",
    "High user count. You are special for being able to access this!",
    "At user limit, you got in just in time!",
    "@OutRed",
    "Imagine not being smart...",
    "Certified Dingus",
    "You are special.",
    "*farts intensely loud*",
    "Escape the Matrix!",
    "Escape the Matrix! -Top G",
    "Burger King... Booger King... wait what",
    "Made by OutRed",
    "Play more games now",
    "Now with 2 unblockers!",
    "Did you know this website has an unblocker?",
    "Did you know this website... ah nevermind i forgot",
    "Why are you looking at this? Go play more games",
    "Look Jeff, it's looking at us again!",
    "Now with actually funny phrases that go here",
    "W rizz",
    "L rizz",
    "You're the rizzler!",
    "You're the rizzard of oz!",
    "I'm an active developer, stay tuned for more on this site.",
    "An incredible unblocked games website, that offers so much more.",
    "From now on the cheese emoji means the skull emoji",
    "Brokie",
    "Imagine not having 20 million power...",
    "*pov me trying to be funny*",
    "Don't do drugs kids.",
    "Don't be bored, play more games",
    "deez",
    "9 + 10 = 21",
    "What's 9 + 10? 21 :/",
    "Breathe air!",
    "Don't vape kids",
    "What color is your honda ridgeline?",
    "What's cookin?",
    "Bruh",
    "Dude",
    "Bet",
    "Yo",
    "By using this site, you are accepting the TOS.",
    "Limited availability!",
    "Han shot first!",
    "Fartpuppet",
    "Meme this",
    "Let's go",
    "Get back to the games",
    "Get a life",
    "Get a life nerd",
    "Quit actin' like ya know the way",
    "eeeeeeeeeeeeeeee",
    "Prepare yourself soldiers, school is a challenge.",
    "Play this site for a couple hours, then go do your homework.",
    "Proven fact: By playing online games it increases your creativity, therfore increasig your grades!",
    "sussy baka",
    "Avengers, assemble!",
    "*silent moment of cringe*",
    "Get back to your schoolwork",
    "Reminder: Do your math homework!",
    "Hot digity dawg",
    "Gosh dang!",
    "Made with Atom!",
    "Don't go to Terminist",
    "jimmy neutron certified",
    "Lookout for walkers",
    "See if you can catch the easter eggs",
    "Oh you're reading this again?",
    "Someones actually reading this!",
    "Do people actually read this?",
    "Stop throwing pizzas on the roof!",
    "e",
    "My name is Gustavo but you can call me Gus.",
    "brrrrrrrr",
    "sub to patreon and your name goes here btw",
    "inflation...",
    "Remember when the white vans used to say free candy? Now they have the free crossed out and say 1$. Inflation man, I'm telling ya",
    "Cuh",
    "Ads or not?",
    "Press: CTRL + SHIFT + Q + Q to get rid of blocking systems.",
    "Delete System 32 on your windows computer, it deletes blocking systems.",
    "Members Only",
    "Lecoco is the king of Rapi SMP (True OG's will know)",
    "I see you Rapi (or not)",
    "I see you Blocky (or not)",
    "I see you Exile (or not)",
    "I see you whoever you are",
    "help (jk)",
    "When will these ever end...",
    "We are living in the Matrix.",
    "Brrrrr, skibiti dop dop dop dop yes yes yes skeep skibitideep skibiti bobbity bobbity yes yes",
    "Canadians... eh?",
    "Hello world!",
    "Oh I'm the slim shady yes im the slim shady",
    "Supa Hot Fire",
    "You got school tomorrow. Do that homework, clean them clothes, get ready.",
    "Did you know you have rights? - Saul Goodmen",
    "brooooooooo",
    "Wowzers! You made the last spot!",
    "I have 50 million power in Rise of Kingdoms!",
    "Every YT video be like: Sponsored by RAID, SHADOW LEGENDS!",
    "Vaping makes you shorter!",
    "Breathe air! Get rid of that vape.",
    "Sub 2 OutRed on YT",
    "Waltuh yo",
    "This actually works???",
    "nutz",
    "Dee Snutts",
    "Delete TikTok, your life will be a lot better. Trust me bro.",
    "You'll get all the girls by using this site!",
    "Now hiring!",
    "Is it just me... or is backrooms freaky"
  ];

  function getRandomPhrase() {
    return phrases[Math.floor(Math.random() * phrases.length)];
  }